import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="font-body bg-background flex flex-col items-center text-text-primary dark:bg-background-dark dark:text-text-primary-dark transition-all duration-700">
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
